language: node_js
cache: yarn
node_js:
  - node
  - "10"
matrix:
  include:
    os: windows
    node_js: node
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/api
  on:
    branch: master
    node_js: node
    os: linux
